### ISSUE TITLE
publishing to npm

### ISSUE THREAD

**Issue by thetutlage** [crypto-utils/keygrip#22]
Version 2 seems great , when planning to push npm ?

**Comment by dougwilson** [comment]
Actually, fairly soon. Express 3.x support just finished and now working on getting all new versions of modules that were suppressed from that (plus Node.js 4.x is bringing new life into it).

**Comment by thetutlage** [comment]
Any updates ?

**Comment by ryansobol** [comment]
What is holding this up?

**Comment by dougwilson** [comment]
The issues outlined in the other open issues.

**Comment by jessaustin** [comment]
If you're talking about the failing test on the pr crypto-utils/keygrip#29, this really seems like a problem with Travis integration, because when I `git clone` it, `npm i`, `npm t`, I get: 
```
  6 passing (52ms)
```
Is there a way to rerun Travis, this time maybe without `v0.8` support?

**Comment by dougwilson** [comment]
No, that's not what I'm talking about.

**Comment by jessaustin** [comment]
OK, that's too mysterious for me. Thanks and good luck!

**Comment by dougwilson** [comment]
I'm not at a computer to look it up, but I don't see anything talking about a Travis CI issue in the PR you linked, only that the actual content needs to be reviewed. I have no idea what you are referring to, and I'm not able to look up what I'm talking about right now. There is some long issue about how the functions on master are unsafe and that has not been addressed yet,so of course we are not going to publish.

If there is some specific fix you would like me to release, let me know what it is and I can backport it and release a 1.x patch version to npm.

**Comment by ryansobol** [comment]
> If there is some specific fix you would like me to release, let me know what it is and I can backport it and release a 1.x patch version to npm.

Using sha256 instead of sha1.

**Comment by dougwilson** [comment]
> Using sha256 instead of sha1.

What? Version 1.0.1 already supports sha256. Can you be more specific in the request?
