### ISSUE TITLE
why two more keys ,how  keys  fresh

### ISSUE THREAD

**Issue by sanrudongfeng** [crypto-utils/keygrip#30]
The keylist is an array of all valid keys for signing, in descending order of freshness; new keys should be unshifted into the array and old keys should be popped.

The tradeoff here is that adding more keys to the keylist allows for more granular freshness for key validation, at the cost of a more expensive worst-case scenario for old or invalid hashes.

I don’t understand why keys is more than one?and also I don't find api about how "The keylist is an array of all valid keys for signing, in descending order of freshness",can you show me a example??????

**Comment by dougwilson** [comment]
> I don’t understand why keys is more than one?

It's needed in order to do key rotation.

> and also I don't find api about how "The keylist is an array of all valid keys for signing, in descending order of freshness",can you show me a example??????

I'm not sure I understand your question here, if you can state it a different way, perhaps?
