### ISSUE TITLE
Debug package vulnerability with ReDoS

### ISSUE THREAD

**Issue by edisoncast** [crypto-utils/keygrip#31]
Currently you are using [debug package](https://www.npmjs.com/package/debug) with version 2.1.3
which includes ms in version 0.7.0 [vulnerable](https://nodesecurity.io/advisories/46). 

The solution is upgrade debug package version to latest.

Could you upgrade this? I'll generate the PR

Thanks

**Comment by dougwilson** [comment]
Sure, but the version that is published to `npm` does not include the dependency on `debug`.  Here is the `package.json` as published to npm: https://github.com/crypto-utils/keygrip/blob/1.0.1/package.json

**Comment by dougwilson** [comment]
I'm not sure how the `develop` branch got onto `master`, but I rolled back `master` to reflect what is on `npm`, so there is no longer any dependencies, as published.
