### ISSUE TITLE
Engine bump for next semver major

### ISSUE THREAD

**Issue by sehrope** [crypto-utils/keygrip#36]
I have some ideas for things to improve in this module but it's kind of a pain to have them all work and tested with the ancient versions of node referenced in the engines block (>=0.6). For reference the last release of 0.6 was July 2012 and it predates any formal long term maintenance policy. The oldest LTS release was 0.10 and that reached end of life Oct 2016.

Any thoughts / objections to having the next semver major of this module support only current LTS versions? As of writing that would be 8+. Note that I'm not suggesting a rolling LTS-only policy, only that the next major version could leverage 8+ code and APIs.

**Comment by dougwilson** [comment]
So the question would be if it's actually impossible to support in older versions or just harder. Bumping it is doable, but doing so would also end up by extension bumping the Node.js required in all the modules that depend on this module. 

The typical thought is that it needs to be impossible to actually accomplish something in the older versions. If you just need help getting it to work in current and old I can always lend a hand as well.

**Comment by sehrope** [comment]
Likely more in the "just harder" category. One annoying thing I ran into is that even shims like buffer-from don't support 0.6 as internally it calls `Buffer.isEncoding(...)` which is >=0.9.

Figured I'd see the overall policy on bumping majors before digging into a a more expansive workaround.
