### ISSUE TITLE
why use `0 in keys`?

### ISSUE THREAD

**Issue by weizhiqimail** [crypto-utils/keygrip#39]
I find  https://github.com/crypto-utils/keygrip/blob/70be53a7c8cd2c8e2f30036d2bbb40e911562542/index.js#L17

I guess you want check `keys` is array value，but `0 in keys`, I think we can't use it check array, because if `keys = {0: 1}`, then check `0 in keys`, it's `true`.

BUT,  https://github.com/crypto-utils/keygrip/blob/70be53a7c8cd2c8e2f30036d2bbb40e911562542/index.js#L37 , you use `keys.length`. if keys type is object, this `for` will not work.

so, I think use `0 in keys` to check `keys`  is array, it will has some problems.

Although `crypto.createHmac` will report errors when I use objects, the keys parameter is passed to node in the sign method of keygrip, so I still think the potential problem from third lib, not node.

Maybe I am wrong. Looking forward to your reply.

**Comment by dougwilson** [comment]
The check you are referring to is not a type check, it is simply to verify that there is something set in `keys[0]`, whatever type of value `keys` is.
